#!/bin/sh

case "$1" in
	start)
		/usr/local/bin/hypnotoad cvupdater
	;;

	stop)
		if [ -f hypnotoad.pid ]; then
			/usr/local/bin/hypnotoad -s cvupdater
		else
			echo "hypnotoad is not started!" >&2
			exit 1
		fi
	;;

	restart)
		if [ -f hypnotoad.pid ]; then
			/usr/local/bin/hypnotoad -s cvupdater
			/usr/local/bin/hypnotoad cvupdater
		else
			echo "hypnotoad is not started!" >&2
		fi
	;;

	status)
		if [ -f hypnotoad.pid ]; then
			echo "hypnotoad seems to be running"
		else
			echo "hypnotoad is not running"
		fi		
	;;
	*)
		echo "Usage: ctl.sh {start|stop|restart|status}" >&2
		exit 1
		;;
esac

exit 0
