requires 'DBIx::Class', '0.082820';
requires 'Modern::Perl', '1.20140107';
requires 'Data::Printer', '0.35';
requires 'SQL::Translator', '0.11021';
requires 'DateTime::Format::SQLite', '0.11';
requires 'DateTime::Format::ISO8601', '0.08';
